### ISSUE TITLE
Pair Example: Busy Blocking?

### ISSUE THREAD

**Issue by ax3l** [nevstop/lvZMQ-Tutorial-Example#1]
Hi,

we (cc @ag6520) are trying the pair example with TCP in LabView 2018. We use a simple one-sender-one-receiver model.

We had to change the connection to open/listen explicitly to 127.0.0.1 instead of `*`, so client and server could find each other.

After this fix, we still experience an unusable experience. It seems the sender-receiver busy-polls both on sender and receiver, which gets LabView stuck. Is there any way to change this, e.g. to linger around or poll less often?

Independent of the issue above, to the examples follow the recommended practices for a clean exit?
http://zguide.zeromq.org/page:all#Making-a-Clean-Exit

**Comment by nevstop** [comment]
Hi @ax3l . I just missed the issue notification.  Sorry for a late reply.

Actually, The pair example works well here. no change needed, you could make it running. Screenshot atteched. I tested it with LabVIEW 2014 and labview-zmq-3.4.1.107.vip( Uploaded to the repo now). You can try it.

![image](https://user-images.githubusercontent.com/8196752/81796243-c17e9c80-953f-11ea-99ba-aa598c69024d.png)

For the "clean exit" question, I think it follows the rule in my option. The application will hang at "zmq_ctx_destroy.vi" if you don't close all sockets in the context.

**Comment by ax3l** [comment]
Thanks a lot, @nevstop!
